### ISSUE TITLE
Use the Cake Contrib Icon

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Transifex#6]
Thanks again for creating this Cake Addin, we really appreciate the effort that you have put in to creating it.  

We, the Cake Team, recently announced a new Cake Contrib Icon, details of which can be found here:

http://cakebuild.net/blog/2017/06/new-cake-contrib-icon

Would you consider changing the nuspec file for your NuGet Package to use this new Cake Contrib Icon?  If so, the recommended URL to use is:

https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png

Details of the above URL can be found in the repository here:

https://github.com/cake-contrib/graphics

Please let me know if you have any questions.

**Comment by AdmiringWorm** [comment]
Well, I don't really mind adding the Cake Contrib icon.
Just curious though, would it be okay if I made a few changes on it (just for this addin).
I'm thinking of trying to include some of the colors used in the transifex logo as well (for instance, replacing the yellow in the current cake loko with the background color from the following icon).
![image](https://user-images.githubusercontent.com/1474648/27616798-9a056d24-5bb2-11e7-9dc2-8bbb196ca24d.png)

**Comment by gep13** [comment]
@AdmiringWorm let me discuss it with the team...

**Comment by AdmiringWorm** [comment]
Just to give an indication of what I mean, i tested out a few difference versions.
What I would like is one of the following:

![cake-transifex - 1](https://user-images.githubusercontent.com/1474648/28390750-aadf1156-6cdb-11e7-887e-0a916544885b.png)
![cake-transifex - 2](https://user-images.githubusercontent.com/1474648/28390753-aaf0bb54-6cdb-11e7-9858-cfe78263199d.png)
![cake-transifex - 3](https://user-images.githubusercontent.com/1474648/28390752-aae7e98e-6cdb-11e7-9f20-251a2acb7718.png)
![cake-transifex - 4](https://user-images.githubusercontent.com/1474648/28390751-aae30d74-6cdb-11e7-9fcf-820309306034.png)


Honestly, I like the first one.

@gep13 ^^

**Comment by gep13** [comment]
@AdmiringWorm sorry for taking so long to get back to you on this!  I have spoken with the team and while our preference is that you use the original logo as is, there is nothing to stop you changing it as you want.  We would ask that you follow the terms of the license as described here though:

https://creativecommons.org/licenses/by/4.0/

Of the four, I think I would pick either the first or the second 😄

**Comment by AdmiringWorm** [comment]
I've decided to just use the vanilla icon for now. But that could change sometime in the future though.
